USE CasaPopular;

IF (SELECT COUNT(*) FROM Familias) = 0
BEGIN
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
END;