//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.casa.popular.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("domain.casa.popular.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE CasaPopular;
        ///
        ///IF (SELECT COUNT(*) FROM Familias) = 0
        ///BEGIN
        ///	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
        ///	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
        ///	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
        ///	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
        ///	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES (NEWID(),GETDATE(), 1)
        ///	INSERT INTO Familias (Id, CreateAt, IsActive) VALUES ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FamiliaSeed {
            get {
                return ResourceManager.GetString("FamiliaSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE CasaPopular;
        ///
        ///IF (SELECT COUNT(*) FROM Pessoas) = 0
        ///BEGIN
        ///	MERGE Pessoas WITH (HOLDLOCK) AS TARGET USING (VALUES (NEWID(), (SELECT TOP 1 * FROM STRING_SPLIT((SELECT &apos;NOME &apos; + CONVERT(varchar(255), NEWID())), &apos;-&apos;)), (SELECT 3 + CRYPT_GEN_RANDOM(1) % 80), &apos;F&apos;, (SELECT 100 + CRYPT_GEN_RANDOM(1) * 3), (SELECT TOP 1 Id FROM Familias ORDER BY NEWID()), GETDATE(), 1)) AS SOURCE (Id, Nome, Idade, Sexo, Salario, FamiliaId, CreateAt, IsActive) ON TARGET.Nome = SOURCE.Nome WHEN NOT MATCHED BY TARGET THEN INSER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PessoaSeed {
            get {
                return ResourceManager.GetString("PessoaSeed", resourceCulture);
            }
        }
    }
}
